### ISSUE TITLE
create and update contribution.md

### ISSUE THREAD

**Issue by darshan45672** [Ajiet-DevNation/DevNation-CMS#18]
the contribution.md file must be updated and enchaced

**Comment by gaureshpai** [comment]
![create-new-issue](https://github.com/user-attachments/assets/1fc24dcf-cd1b-45cf-ac92-7e9f3cc693ce)
![fork](https://github.com/user-attachments/assets/4aa093c8-236c-428f-97d0-f23c9d1a79fb)
![fork-2](https://github.com/user-attachments/assets/87872869-6aa4-4c70-a699-56dbbeb49102)
![issues](https://github.com/user-attachments/assets/bdee4836-7db3-45aa-a3bc-c5af644e8a8b)
![pull](https://github.com/user-attachments/assets/0f2f0ded-5f3a-4492-90c0-e9d56ef3b45a)
![star](https://github.com/user-attachments/assets/1ddb9b66-c0d6-409d-80c0-42650673a012)
