### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by jtuluve** [Ajiet-DevNation/DevNation-CMS#35]
A file containing contributing guidelines should be added. (CONTRIBUTING.md)
Currently, this repository lacks a CONTRIBUTING.md file, which can guide new contributors on how to get involved, report issues, and contribute code.

Having a well-documented CONTRIBUTING.md will help:
- Provide instructions on how to set up the project locally
- Outline the process for submitting pull requests
- Define any code style or testing requirements
- Include guidelines on filing issues and suggesting features
- Clarify how contributors can get in touch for questions or clarifications

The guidelines should follow standard practices of open source contribution.

**Comment by darshan45672** [comment]
reference to issue #18

**Comment by jtuluve** [comment]
My bad😬

**Comment by sojijr** [comment]
This issue should be closed please, to avoid confusion as it has been clarified

**Comment by darshan45672** [comment]
yea sure @sojijr
